### ISSUE TITLE
A string of a second shipping method doesn't appear

### ISSUE THREAD

**Issue by YossiAharon** [decarvalhoaa/woo-poly-integration#5]
When adding a second shipping method, it doesn't appear in the strings lists. 
There are only two strings related to shipping methods:
`woocommerce_flat_rate_shipping_method`
`woocommerce_local_pickup_shipping_method`

**Comment by decarvalhoaa** [comment]
Hi,
is the second method you want to add is enable in woocommerce, i.e. you see it in the Cart and Checkout pages?

**Comment by YossiAharon** [comment]
Yes, the second method is active and enabled in the cart. The second method is also flat rate type. WooCommerce changed recently in 2.6 version the old way of shipping to shipping zones. I'm not sure if this code is updated for it.

**Comment by decarvalhoaa** [comment]
No, I haven't yet test it with WC 2.6. Generally I wait 1 or 2 months before updating, since the first weeks when new code comes out has always some issues that were missed in QA and I'm don't want to test all the small maintenance releases because is time consuming. I will probably install WC 2.6 today on my Dev environment and start debuting. 

Thanks for reporting the issue. Very much appreciated.

**Comment by decarvalhoaa** [comment]
Fixed in development branch: targeted for v1.0.0
